FROM python:3.11 as base
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
# ---- Distroless Stage in SAME file without multistage ----
# THIS IS ONLY FOR DEMO, NOT PRODUCTION.
FROM gcr.io/distroless/python3
WORKDIR /app
COPY --from=base /usr/local /usr/local
COPY --from=base /app /app
EXPOSE 8080
CMD ["python3", "/app/app.py"]
